### ISSUE TITLE
[Bug]: Scroll to top when item is added

### ISSUE THREAD

**Issue by naveenenushan** [DerYeger/vue-masonry-wall#15]
### Description

when we use to insert new item to item array using this  

this.items = [...this.items, item]

view is refreshing and scrolled to top

### Reproduction

Just try to remove item in bottom https://vue-masonry-wall.yeger.eu 
its remove and scrolled to top ( view refresh)

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Hey @naveenenushan, the latest version of this library (3.0.8) should have a fix for this issue.

**Comment by naveenenushan** [comment]
sure, let me check

**Comment by naveenenushan** [comment]
working great,
Thank you very much.

Just Update the [site](https://gifiw.com/) with new version

**Comment by DerYeger** [comment]
Glad to hear it. Thank you very much for testing!

**Comment by SliiCer** [comment]
Hey @DerYeger thanks for this great library ;)
Sorry but for me, the issue persiste when i do a 

`this.list.push(...list);`

Always go to the top..

**Comment by naveenenushan** [comment]
> Hey @DerYeger thanks for this great library ;) Sorry but for me, the issue persiste when i do a
> 
> `this.list.push(...list);`
> 
> Always go to the top..

try this
this.listA = [...this.listA,...result.data.data]

also check the installed version

**Comment by SliiCer** [comment]
Wow quick answer ^^
Yes i'm on 3.0.8!

But no change with your proposition

**Comment by SliiCer** [comment]
Hey @DerYeger thanks for your answer!

I've tried both solutions without chance.
`this.list.push(...list);` or `this.list = [...this.list,...result.data.data]` scroll to top

I gonna try to do a example but it's a bit tricky to reproduce..

**Comment by naveenenushan** [comment]
@SliiCer 
Are u fetching data from a API? and do u use it as a something like infinity loading ? if yes, try to prevent requesting API call while another API call on request. use a variable for prevent it.

like `this.loading = true;` and check before it call again

**Comment by SliiCer** [comment]
@naveenenushan Yes i use Laravel for API with the `.paginate()` functionality. 
It's a simple page incrementation on button click with Axios to call API and in the `.then()` i do the `this.list = [...this.list,...result.data.data]`.

But i found a solution ^^ 
I did a `.groupBy()` on front side with Lodash and now i do it in Laravel side and it's work perfectly..

So voilà, thanks you for your tips!

**Comment by naveenenushan** [comment]
> @naveenenushan Yes i use Laravel for API with the `.paginate()` functionality. It's a simple page incrementation on button click with Axios to call API and in the `.then()` i do the `this.list = [...this.list,...result.data.data]`.
> 
> But i found a solution ^^ I did a `.groupBy()` on front side with Lodash and now i do it in Laravel side and it's work perfectly..
> 
> So voilà, thanks you for your tips!

Glad to hear that. Cool

**Comment by zhangv** [comment]
I've got this "scroll to top" thing with vue2-masonry-wall v2.3.1, is there any fix on this issue?

**Comment by DerYeger** [comment]
> I've got this "scroll to top" thing with vue2-masonry-wall v2.3.1, is there any fix on this issue?
> 
> 

If you have the component inside a scrolling container, you'll have to pass that container as an argument, as described in the docs.

**Comment by zhangv** [comment]
Thanks for the reply. I tried :

`
:scroll-container="$refs.scrollContainer"
`

Not working. It's quite weird that if I change the "adding items" to the static(rather the axios call in the real case), it worked quite normal. However once I switch it to the one calling the remote API, it acts like redrawing everything from the top.

Tried several scenarios (no image, local image, remote image). It seems that the scroll position is calculated dynamically by the content of the masonry container. However, the remote images require some loading time, during this loading period, the calculating got the wrong height(which is 0 by that time).

**Comment by DerYeger** [comment]
> Thanks for the reply. I tried :
> 
> `:scroll-container="$refs.scrollContainer"`
> 
> Not working. It's quite weird that if I change the "adding items" to the static(rather the axios call in the real case), it worked quite normal. However once I switch it to the one calling the remote API, it acts like redrawing everything from the top.
> 
> Tried several scenarios (no image, local image, remote image). It seems that the scroll position is calculated dynamically by the content of the masonry container. However, the remote images require some loading time, during this loading period, the calculating got the wrong height(which is 0 by that time).

Ah I see. If the component height is changed dynamically (e.g., by the image taking multiple Vue ticks to load), this library does not account for that.
In theory it's possible to watch for resizes of all children, but that would ruin performance and may end up in endless re-layouts.
I don't think there's a good solution here, sorry.

**Comment by gspgsp** [comment]
great！ this issue is helpful for me.
