### ISSUE TITLE
Making bottom more even

### ISSUE THREAD

**Issue by MarisKay** [DerYeger/vue-masonry-wall#27]
Hey there, great work, i truly enjoy your component! A quick question - let's say if i have 100 different size pictures loaded, bottom line becomes quiet uneven. Would it be possible to somehow add a feature that tosses each column items in a way so it minimizes the unevenness at the very end? Got the idea? Thanks

**Comment by DerYeger** [comment]
Thank you very much!

Unfortunately, I don't think that is possible without knowing the height of all components in advance.
This component inserts element by element. This approach enables using components with unknown or dynamic size, but prevents an optimisation like you described in advance.
It could only work by re-adding all elements every time (and adding the balancing logic), but this would cause huge layout shifts.
