### ISSUE TITLE
[Bug]: can not work in vue3

### ISSUE THREAD

**Issue by leeboo** [DerYeger/vue-masonry-wall#28]
### Description

`<masonry-wall :items="items" >.....`

below code not work:
`  setup (props: any, context: any) {
    const items = ref<any>(....array.)
    return {
      items
    }
  }`

### Reproduction

`<masonry-wall :items="items" >.....`

below code not work:
`  setup (props: any, context: any) {
    const items = ref<any>(....array.)
    return {
      items
    }
  }`

### Preferences

- [X] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Hello,


what exactly is the issue?
Did you properly import the component as described in the REAMDE?

```ts
import { createApp } from 'vue'
import MasonryWall from '@yeger/vue-masonry-wall'

const app = createApp()

app.use(MasonryWall)
```

**Comment by DerYeger** [comment]
I'll close this, since the report is incomplete.
