### ISSUE TITLE
Vue 2 support?

### ISSUE THREAD

**Issue by ux-engineer** [DerYeger/vue-masonry-wall#3]
Hi, and thanks for this interesting package!

First I treid vue-masonry-wall on a project with Vue 2 composition API and TypeScript. It had some issues so switched to MasonryJS based vue-masonry. However, it has some responsive quirks when using it with bootstrap grid... So keeping an eye out for alternatives.

This is looking promising. Hopefully this gets developed and maintained in the future as well.

Many of us seem to be stuck with Vue 2 until some major libraries release Vue 3 support. In our case, Bootstrap Vue library has went silent although its a hugely popular library, and they started developing Vue 3 support already late last year...

Would it be much work to support Vue 2, i.e. with using [vue-demi](https://github.com/vueuse/vue-demi) package?

**Comment by DerYeger** [comment]
Hi, it seems `vue-demi` is not designed for components (see https://github.com/vuejs/rollup-plugin-vue/issues/427#issuecomment-753867261).

I tried it out regardless, but could not get it to work.
What I did notice is an increase of the bundle size by 300%.
So even if it worked it probably wouldn't be justified to use `vue-demi` in this case.

However, I could create a second repo and publish a Vue 2 version there if that would help you.

**Comment by ux-engineer** [comment]
Interesting, I wasn't aware of that issue between components and plugins with vue-demi. Thanks for clarifying this, and for your fast action on this :)

**Comment by DerYeger** [comment]
> Interesting, I wasn't aware of that issue between components and plugins with vue-demi. Thanks for clarifying this, and for your fast action on this :)

You're welcome! Check out https://github.com/DerYeger/vue2-masonry-wall for the Vue 2 version.

**Comment by DerYeger** [comment]
I added a link to the [Vue 2 version](https://github.com/DerYeger/vue2-masonry-wall) of this component to the README.
