### ISSUE TITLE
[Question]: Double width or height?

### ISSUE THREAD

**Issue by notflip** [DerYeger/vue-masonry-wall#31]
### Description

Is it possible to achieve a layout in which I can assign certain cols as double width, double height or both? To have some variation?

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
The height of items depends on the items themselves, so that's certainly possible.

However, all columns have the same width.

**Comment by DerYeger** [comment]
v3.7.0 now supports differing column widths.
