### ISSUE TITLE
Typescript issue when building

### ISSUE THREAD

**Issue by Wouter01** [DerYeger/vue-masonry-wall#37]
When trying to build my website with `npm run build`, I get this TypeScript error:

```
node_modules/@yeger/vue-masonry-wall/dist/types/index.d.ts:2:23 - error TS2307: Cannot find module '../src/masonry-wall' or its corresponding type declarations.

2 import component from "../src/masonry-wall";
```

This was not happening at version 3.0.26, but it is for all newer versions.
I think this is because the directory tree changed between the versions:

```
v3.0.26
└── vue-masonry-wall
    ├── LICENSE
    ├── README.md
    ├── dist
    │   ├── masonry-wall.es.js
    │   ├── masonry-wall.umd.js
    │   └── types
    │       └── src
    │           ├── index.d.ts
    │           └── masonry-wall.d.ts
    ├── package.json
    └── src
        └── masonry-wall.vue
```
```
v3.0.31
└── vue-masonry-wall
    ├── LICENSE
    ├── README.md
    ├── dist
    │   ├── masonry-wall.es.js
    │   ├── masonry-wall.umd.js
    │   └── types
    │       ├── index.d.ts
    │       └── masonry-wall.d.ts
    ├── package.json
    └── src
        └── masonry-wall.vue
```

The typescript error in v3.0.31 is gone when I change
`import component from "../src/masonry-wall";` to `import component from "./masonry-wall";`

I'm not sure how to fix this, but I would suspect it has something to do with this:
https://github.com/DerYeger/vue-masonry-wall/blob/931e2361b02392158314d8a96d5474d8882ee36b/tsconfig.json#L23

Could you help me out with this?
Thanks!

**Comment by DerYeger** [comment]
Thanks for reporting this issue!

The problem is caused by an update to `vite-plugin-dts`. It changed the directory structure as noted above.
I then changed the `types` path of this package but didn't notice that the generated type definitions are invalid.

I'm not quite sure how to fix this as the options of `vite-plugin-dts` don't seem to impact the output.

**Comment by DerYeger** [comment]
This should be fixed now. Extra build steps were added to ensure this won't happen again (including building the demo against the dist files and using vue-tsc to check the types).
