### ISSUE TITLE
[Bug]: invalid CSS style

### ISSUE THREAD

**Issue by or2e** [DerYeger/vue-masonry-wall#41]
### Description

masonry-column has an invalid format flex-basis property
https://github.com/DerYeger/vue-masonry-wall/blob/master/src/masonry-wall.vue#L14

`0 -> '0%'`

### Reproduction

1/ disable JS in browser
2/ set props `ssrColumns`, for example `:ssrColumns='3'`

columns have different widths due to unapplied property `flex-basis`

### Preferences

- [x] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Thank you for the report. It seems this is an issue of Nuxt 3 removing valid CSS properties, as `flex-basis: 0` is [indeed valid](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis).

I saw your PR #42, but `flex-basis: 0%` is different than `flex-basis: 0`, which is what this library needs.
`flex-basis: 0px` should fix the issue with Nuxt 3.

**Comment by or2e** [comment]
ok, I'll MR(PR) fix it later

**Comment by or2e** [comment]
> ok, I'll MR(PR) fix it later
[DerYeger](https://github.com/DerYeger)
rdy
