### ISSUE TITLE
[Bug]: Images not distributed correctly across columns if portion of content added below visible area of screen.

### ISSUE THREAD

**Issue by MarisKay** [DerYeger/vue-masonry-wall#46]
### Description

Images not distributed correctly across columns if more content added below the currently visible area of screen.

### Reproduction

I am displaying a gallery of images where script adds another 25 images if user has scrolled to the very last loaded image.
Initial 2 portions load fantastic and they got distributed across multiple columns as masonry wall should be.

Problem starts if script triggers loading another 25 images and majority of them are not displayed on visible portion of screen (e.g. user has to scroll down more to see them). Images are no more distributed correctly across the columns. Some columns advance by 3, 4 or even 5 images, while others remain empty gaps resulting in exageratedly uneven bottom.

Initially I blamed the way how i added the images, i blamed Quasar framework for its components etc. However, I switched to simple <img> html tags to display images and simple load more button at the end of currently loaded portion. Problem starts to happen exactly at point when biggest portion of newly loaded images appear below the currently visible screen area. Then i tested it by super zooming out the screen (making everything super small  so i have bigger screen area). And guess what - portions that were problematic before - now do render correctly, but .. again, as soon as i go out of the visible screen area - problems start with those portions.

I have also tried to set my loading script to add only +1 image instead of 25 in my portion load script. In this case everything goes smoothly. 

So these two things together => loading images by portions + loading a portion so user has to scroll down to see it, those two things together produce this weird behavior.

I have also attached a video showing it in action (had to blur the pics though). And here i set 10 pics per fetch so it takes several fetches to fill the initial visible screen. Then extra fetch happens when i scroll down and reach the end.
https://www.youtube.com/watch?v=DpfZDot0NXA

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by MarisKay** [comment]
And finally, running all these tests for more than an hour - several times the problem appeared in first few portion fetches, so at the end it might even not be caused by rendering additional portion off-scrreen. 

Would be interesting to see your online demo outputing packs of N images rather than adding a single div at a time.

**Comment by MarisKay** [comment]
Thank you so much for adding 10 item option. 

Looked again at your html output - each div has a known height you set in your div's style. 

So i wonder, is it supposed to work with images where each element is <img style="width:100%".. > without knowing images height or width. It should just fill the 100% of column horizontally, and height should turn out without losing proportions?

If possible, could you try this scenario on your demo code? I believe it's specific to images, how fast they load and how the size is getting calculated.. and current demo may not even reveal this problem since height is pretty much hardcoded in each div.

Thanks

**Comment by MarisKay** [comment]
Alright, the magic moment has arrived. After nearly a month of going back and forth through different ideas and trying to find out how it could work with images - finally I found a solution. Yes, that involves knowing your pic dimensions!

The magic ingredient to style that should be applied to img is not just width: 100% (that will lead to the problem described above), but this:

`style="width:100%; aspect-ratio: sizex/sizey"`

where sizex and size y is your actual image width and height. And once the system knows the aspect ratio, seems it is not hard for it to calculate actual dimensions on responsive output.

I really hope the author will include this extra finding in the docs so other users trying to make it work with images wont have to waste precious time finding this truth by themselves.

Cheers!

**Comment by DerYeger** [comment]
Thank you very much for the investigation!
I added a section about the limitations concerning dynamically changing item height to the README.
