### ISSUE TITLE
[Help] Configurate the plugin

### ISSUE THREAD

**Issue by BenjaminOddou** [DerYeger/vue-masonry-wall#59]
Hello,

I have some problems using this plugin in a nuxt 3 app. My following config doesn't seems to work, I have twice my images 😅 and it's lagging a lot :

```vue
// Page.vue
<script setup lang="ts">
const { data: images } = useFetch<ImageKit[]>('/api/imgkit') // It returns array of objects
</script>

<template>
      <MasonryWall
        :items="images"
        :ssr-columns="3"
        :column-width="300"
        :gap="16"
      >
        <template #default="{ image }"> <!-- not sure if that's needed but is not working -->
          <div v-for="image in images" :key="image.filePath"> <!-- removing this line didn't helped -->
            <Transition mode="out-in" @leave="onLeave" @enter="onEnter">
              <nuxt-img
                v-show="image.tags && image.tags.find((tag) => tag === filter)" 
                :src="image.filePath"
                :width="image.width"
                :height="image.height"
              />
            </Transition>
          </div>
        </template>
      </MasonryWall>
</template>
```

EDIT : I ended up with this config but I was wondering if it could be possible to type the `item` element in order to benefit from typescript definitions ? 

```vue
      <masonry-wall
        :items="images"
        :ssr-columns="3"
        :column-width="340"
        :gap="0"
      >
        <template #default="{ item }">
          <Transition mode="out-in" @leave="onLeave" @enter="onEnter">
            <nuxt-img
              v-show="item.tags && item.tags.find((tag) => tag === filter)"
              :src="item.filePath"
              :width="item.width"
              :height="item.height"
              class="pl-5 pr-5 pb-5 sm:pl-0"
            />
          </Transition>
        </template>
      </masonry-wall>
```

Thank you in advance for your help 🙂

**Comment by DerYeger** [comment]
Hi, it seems you already solved your issue?

Regarding the `item` type, see https://github.com/vuejs/rfcs/discussions/436. I don't think there's a good solution right now.

**Comment by BenjaminOddou** [comment]
Hey @DerYeger, Thank you for your response ! 🙂 I found this solution that works great. 

```diff
# Here item returns type any
- <template #default="{ item }">
# Here item returns type ImageKit
+ <template #default="{ item }: { item: ImageKit }">
```

However still don't know why the typescript definitions of the module is not working on my side (still have the `type any` on `MasonryWall` component)
![masonry](https://user-images.githubusercontent.com/85166574/189873534-198fa840-4fd4-425c-97f1-f4a2b51b86ad.png)

FYI : I am using nuxt 3 rc-9

**Comment by DerYeger** [comment]
> Hey @DerYeger, Thank you for your response ! 🙂 I found this solution that works great.
> 
> ```diff
> # Here item returns type any
> - <template #default="{ item }">
> # Here item returns type ImageKit
> + <template #default="{ item }: { item: ImageKit }">
> ```
> 
> However still don't know why the typescript definitions of the module is not working on my side (still have the `type any` on `MasonryWall` component) ![masonry](https://user-images.githubusercontent.com/85166574/189873534-198fa840-4fd4-425c-97f1-f4a2b51b86ad.png)
> 
> FYI : I am using nuxt 3 rc-9

https://github.com/DerYeger/vue-masonry-wall/issues/60 describes how to get type definitions for Vue components.

**Comment by BenjaminOddou** [comment]
Thank you for the support @DerYeger 🙏, I think we can now close this issue 🙂
