### ISSUE TITLE
[Feature]: export type definitions for the main component

### ISSUE THREAD

**Issue by mahdiboomeri** [DerYeger/vue-masonry-wall#60]
### Description

Currently, the `MasonryWall` isn't typed when using Volar (since the library registering through global app components). While this doesn't affect functionality, it'd be nice to have in-editor type support for props.

### Solution

One way of having typed global components is through `custom.d.ts file`:

```typescript
import type { component } from '@yeger/vue-masonry-wall';

declare module 'vue' {
  export interface GlobalComponents {
    MasonryWall: typeof component;
  }
}

export {};
```

### Preferences

- [x] I want to be assigned to and work on this issue myself

**Comment by BenjaminOddou** [comment]
> ### Description
> Currently, the `MasonryWall` isn't typed when using Volar (since the library registering through global app components). While this doesn't affect functionality, it'd be nice to have in-editor type support for props.
> 
> ### Solution
> ```ts
> import type { component } from '@yeger/vue-masonry-wall';
> 
> declare module 'vue' {
>   export interface GlobalComponents {
>     MasonryWall: typeof component;
>   }
> }
> 
> export {};
> ```

Hey @DerYeger, @mahdiboomeri,  in the `index.d.ts` of the module there is :
```ts
export default MasonryWall;
```

so I was wondering if the solution wasn't the following instead of the one you mentioned earlier
```ts
import type MasonryWall from '@yeger/vue-masonry-wall'

declare module 'vue' {
  export interface GlobalComponents {
    MasonryWall: typeof MasonryWall
  }
}

export {}
```
with your solution :
![sol_1](https://user-images.githubusercontent.com/85166574/189899060-ec476ed6-c83b-42a4-8536-d93bbf1f9ffc.png)

with the one ☝️
![sol_2](https://user-images.githubusercontent.com/85166574/189899139-3dbc88be-fa02-4e8b-8e9e-68c7afdb7f23.png)

**Comment by DerYeger** [comment]
Ah yes, there's a slight issue with the workaround.

I'm currently working on a fix that doesn't require any changes on your end.

**Comment by DerYeger** [comment]
Can you let me know if v3.2.0 fixed the issue?

**Comment by BenjaminOddou** [comment]
I downloaded the last version (`3.2.0`) and it is working great ! 😊 Thanks for this update !

**Comment by DerYeger** [comment]
> I downloaded the last version (`3.2.0`) and it is working great ! 😊 Thanks for this update !
> 
> 
> 
> ![screenshot](https://user-images.githubusercontent.com/85166574/189903650-c3a2b2ef-316c-4c86-a3f5-f8f4813168da.png)
> 
> 

Awesome! Thanks for the feedback.

**Comment by DerYeger** [comment]
Also big thanks to @mahdiboomeri for informing me about the global components declaration!

**Comment by BenjaminOddou** [comment]
just a small remarks regarding types, it seems that `:scrollContainer` must be defined in template. Not sure why because it is not required in the `masonry-wall.d.ts`. 🧐

**Comment by DerYeger** [comment]
Interesting, I cannot replicate that locally. What's the error message?

**Comment by BenjaminOddou** [comment]
here is the message :

```sh
Cannot assign type '{ items: ImageKit[]; column width: number; "column width": number; }' to type 'ReservedProps & Partial<{ columnWidth: number; gap: number; rtl: boolean; ssrColumns: number; }> & Omit<Readonly<ExtractPropTypes<{ columnWidth: { type: NumberConstructor; required: false; default: number; }; ... 4 more ...; scrollContainer: { ...; }; }>> & { ...; } & VNodeProps & AllowedComponentProps & ComponentCu...'.
  'scrollContainer' property is missing from type '{ items: ImageKit[]; column width: number; "column width": number; }' but required in type 'Omit<Readonly<ExtractPropTypes<{ columnWidth: { type: NumberConstructor; required: false; default: number; }; elements: { type: ArrayConstructor; required: true; }; gap: { type: NumberConstructor; required: false; default: number; }; rtl: { ...; }; ssrColumns: { ...; }; scrollContainer: { ...; }; }>> & { ...; } & VNode...'.ts(2322)
masonry-wall.d.ts(83, 5): 'scrollContainer' is declared here.
No solution available immediately
```

**Comment by DerYeger** [comment]
Hmm, since I can't replicate it locally, I'm not sure how to fix it. Let me know if you have any ideas.

**Comment by BenjaminOddou** [comment]
I think it is because the property scrollContainer doesn't have default value. If I append in `masonry-wall.d.ts`  :

```diff
    scrollContainer: {
        type: null;
        required: false;
+       default: null;
    };
```

I don't have the error popping

**Comment by BenjaminOddou** [comment]
@DerYeger no more error now thanks !! 🙏😊

**Comment by DerYeger** [comment]
> @DerYeger no more error now thanks !! 🙏😊 

Awesome!
