### ISSUE TITLE
Typescript error with strict mode and useFetch composable

### ISSUE THREAD

**Issue by BenjaminOddou** [DerYeger/vue-masonry-wall#69]
Hello,

Since the update of the last nuxt release candidate, typescript is now in strict mode by default as a best practice. I noticed that when using it with this plugin, I have a typescript error. 

```sh
  Impossible to assign type 'undefined' to type 'unknown[]'.ts(2322)
```

[Context](https://github.com/nuxt/framework/issues/8747#event-7747341452) with strict mode enable in nuxt

What I am proposing is to have default: undefined in the `masonry-wall.d.ts` :
```ts
    items: {
        type: ArrayConstructor;
        required: true;
        default: undefined; // new line
    };
```

**Comment by DerYeger** [comment]
It's intended that `items` cannot be `undefined`.

Please try passing an empty array instead of `undefined` (by e.g., using nullish coalescing `:items="myItems ?? []"`).

**Comment by BenjaminOddou** [comment]
@DerYeger indeed it's working like a charm ! Thank you for your support 🙂
